openapi: 3.0.0
info:
  title: Roadside Assistance Admin API
  version: 1.0.0
  description: API endpoints for admin dashboard actions
servers:
  - url: http://localhost:3000
paths:
  /admin/login:
    post:
      summary: Admin login
      tags: [Admin]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
        401:
          description: Invalid credentials
  /admin/users:
    get:
      summary: List all users
      tags: [Admin]
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    email:
                      type: string
                    role:
                      type: string
                    name:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
    patch:
      summary: Update user (role, status, etc)
      tags: [Admin]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
      responses:
        200:
          description: Updated user
        404:
          description: User not found
    delete:
      summary: Delete user
      tags: [Admin]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        204:
          description: User deleted
  /admin/requests:
    get:
      summary: List all service requests
      tags: [Admin]
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of service requests
    patch:
      summary: Update service request status
      tags: [Admin]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        200:
          description: Updated request
  /admin/ratings:
    get:
      summary: List all ratings/reviews
      tags: [Admin]
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of ratings
    delete:
      summary: Delete rating
      tags: [Admin]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        204:
          description: Rating deleted
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
